version: "3"
service:
  db:
    image: "postgres: latest"
    container_name: "postgres_docker"
    environment:
        - POSTGRES_USER = postgres
        - POSTGRES_PASSWORD = "Welcome"
        - POSTGRES_DB = conference_app
    ports:
        - "5432:5432" 