version: "3"
services:
  postgres:
    image: "postgres:11.5-alpine"
    container_name: "postgres_docker"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Welcome
        POSTGRES_DB: conference_app
    ports:
        - "5432:5432" 
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        
  app:
    image: "springboot-api:v2"
    container_name: "api"
    environment:
        - DB_URL=jdbc:postgresql://postgres_docker:5432/conference_app
        - DB_USER=postgres
        - DB_PASSWORD=Welcome
        - ELASTICSEARCH=http://elasticsearch:9200
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=user
        - RABBITMQ_PASSWORD=password
        - RABBITMQ_QUEUE=AddSession.Queue
    ports:
        - "8080:5005"
    depends_on:
      - postgres
      - apmserver
      - rabbitmq

  worker:
    image: "springboot-worker:v3"
    container_name: "worker"
    environment:
        - DB_URL=jdbc:postgresql://postgres_docker:5432/conference_app
        - DB_USER=postgres
        - DB_PASSWORD=Welcome
        - ELASTICSEARCH=http://elasticsearch:9200
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=user
        - RABBITMQ_PASSWORD=password
        - RABBITMQ_QUEUE=AddSession.Queue
        - EMAIL_HOST=greenmail
        - EMAIL_PORT=3025
    ports:
        - "8090:5010"
    depends_on:
      - postgres
      - apmserver
      - rabbitmq
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node    
#      - ELASTICSEARCH_USERNAME= elastic
#      - ELASTICSEARCH_PASSWORD= changeme   
#      - xpack.security.enabled= true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana    
    environment:
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD: changeme
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"

  logstash:
    image: logstash:7.9.3
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
#      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: changeme
#      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
#      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"    
    depends_on:
      - elasticsearch
      
  apmserver:  
    build: 
        context: .
        dockerfile: apmserver.dockerfile
    container_name: apmserver
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]      
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch

  rabbitmq:
#    build: 
#        context: .
#        dockerfile: rabbitmq.dockerfile
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    volumes:
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config:ro
        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"

  greenmail:
    image: greenmail/standalone:1.6.1
    container_name: greenmail
    ports:
      - "3025:3025"
      - "3110:3110"
      - "3143:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995"

#  metricbeat:
#    image: metricbeat:v40
#    container_name: metricbeat    
#    volumes:
#     - "./metricbeat/metricbeatinit.sh:/usr/local/bin/metricbeatinit.sh"
#    environment:
#      - setup.kibana.host=kibana:5601
#      - output.elasticsearch.hosts=["elasticsearch:9200"]
#    #command: ["--strict.perms=false", "-system.hostfs=/hostfs", "metricbeatinit.sh" ]
#    #- metricbeatinit.sh
#    depends_on:
#      - elasticsearch
#      - app
#      - kibana
        